# Import libraries

In [1]:
import pandas as pd
import numpy as np 
import os

## Import Data

In [2]:
# setting path to Data Folder

path = r'C:\Documents\Career Foundry\Python\Instacart Basket Analysis\02 Data'

In [3]:
dfm = pd.read_pickle(os.path.join(path, "Prepped Data", "OLD", "orders_products_mergedOLD2.pkl"))

In [6]:
dfm.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,0.0,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Average orders
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Average orders
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Most orders
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Least busy days,Average orders
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Least busy days,Most orders

In [7]:
dfm.shape

(32403007, 17)

In [8]:
df = dfm[:1000000]

In [9]:
df.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,0.0,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Average orders
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Average orders
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Most orders
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Least busy days,Average orders
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Least busy days,Most orders

In [10]:
df.shape

(1000000, 17)

In [11]:
df.groupby('product_name')

In [4]:
df.groupby('department_id').agg({'order_number': ['mean']})

NameError: name 'df' is not defined

In [5]:
dfm.groupby('department_id').agg({'order_number' : ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1                15.457838   1  99
2                17.277920   1  99
3                17.170395   1  99
4                17.811403   1  99
5                15.215751   1  99
6                16.439806   1  99
7                17.225802   1  99
8                15.340650   1  99
9                15.895474   1  99
10               20.197148   1  99
11               16.170638   1  99
12               15.887671   1  99
13               16.583536   1  99
14               16.773669   1  99
15               16.165037   1  99
16               17.665606   1  99
17               15.694469   1  99
18               19.310397   1  99
19               17.175919   1  99
20               16.473447   1  99
21               22.902379   1  99

In [7]:
department_order_num_mean = dfm.groupby('department_id').agg({'order_number' : ['mean', 'min', 'max']})

In [8]:
department_order_num_mean.to_clipboard()

In [6]:
dfm['max_order'] = dfm.groupby(['user_id'])['order_number'].transform(np.max)

In [27]:
df.head(15)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag
0,2539329,1,1,2,8,0.0,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Average orders,10,New customer
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Average orders,10,New customer
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Most orders,10,New customer
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Least busy days,Average orders,10,New customer
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Least busy days,Most orders,10,New customer
5,3367565,1,6,2,7,19.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Average orders,10,New customer
6,550135,1,7,1,9,20.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer
7,3108588,1,8,1,14,14.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer
8,2295261,1,9,1,16,0.0,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer
9,2550362,1,10,4,8,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Least busy days,Average orders,10,New customer
10,2968173,15,15,1,9,7.0,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
11,1870022,15,17,2,16,8.0,196,6,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
12,1911383,15,18,2,11,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,22,Regular customer
13,2715276,15,21,1,9,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer
14,487368,15,22,1,10,14.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer

In [29]:
df['max_order'].value_counts(dropna = False)

5     23869
4     23730
6     23570
7     23310
8     23027
3     22827
9     22800
99    22457
10    21846
11    21800
12    20760
14    20515
13    20388
15    19604
16    18915
17    18846
19    17838
20    17122
18    16882
21    16525
22    16326
23    16250
24    15411
25    15299
26    14839
27    14090
30    13991
29    13841
28    13295
39    12932
34    12859
31    12733
32    12374
33    12295
36    12239
37    11683
38    11628
42    11594
40    11306
35    11258
41    10759
50    10754
47    10474
43    10350
45    10350
46    10204
2     10126
44     9932
49     9800
48     9705
52     9377
98     8826
51     8703
54     8654
53     8180
55     7929
56     7609
57     7090
61     6621
1      5965
58     5713
59     5588
60     5514
62     5065
65     5044
64     5005
67     4996
97     4935
63     4918
68     4274
70     4179
66     4075
74     4073
75     4056
71     3960
73     3686
78     3532
69     3469
72     3428
77     3286
96     3213
76     3088
80     3046
81     2974
82     2906
95     2836
83     2817
79     2750
86     2601
92     2451
94     2397
85     2254
89     2209
90     2073
93     1920
87     1900
88     1889
84     1833
91     1765
Name: max_order, dtype: int64

In [16]:
pd.options.display.max_rows = None

In [18]:
df.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,0.0,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Average orders,10
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Average orders,10
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Most orders,10
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Least busy days,Average orders,10
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Least busy days,Most orders,10
5,3367565,1,6,2,7,19.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Average orders,10
6,550135,1,7,1,9,20.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,10
7,3108588,1,8,1,14,14.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,10
8,2295261,1,9,1,16,0.0,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,10
9,2550362,1,10,4,8,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Least busy days,Average orders,10
10,2968173,15,15,1,9,7.0,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,22
11,1870022,15,17,2,16,8.0,196,6,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,22
12,1911383,15,18,2,11,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,22
13,2715276,15,21,1,9,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,22
14,487368,15,22,1,10,14.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,22
15,2293453,19,2,5,14,6.0,196,3,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,7
16,1973799,19,5,6,12,8.0,196,15,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,7
17,532817,19,7,4,17,6.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Least busy days,Most orders,7
18,1573906,21,10,3,10,6.0,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Most orders,33
19,1593000,31,10,3,8,7.0,196,17,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Average orders,17
20,2231262,31,17,3,11,8.0,196,14,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Most orders,17
21,2580647,43,6,4,16,4.0,196,9,0,Soda,77,7,9.0,Mid-range product,Least busy,Least busy days,Most orders,9
22,2187180,43,9,4,12,3.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Least busy days,Most orders,9
23,2497897,52,1,1,9,0.0,196,4,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,27
24,1318871,52,2,1,10,7.0,196,5,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,27
25,1261384,52,3,1,10,7.0,196,3,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,27
26,580568,52,5,2,10,8.0,196,6,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
27,2428073,52,7,2,7,8.0,196,5,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Average orders,27
28,342306,52,9,1,11,7.0,196,5,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,27
29,1520353,52,10,2,10,8.0,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
30,2542086,52,11,2,9,7.0,196,3,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
31,944694,52,12,1,16,6.0,196,7,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,27
32,1268191,52,15,2,11,8.0,196,3,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
33,1122089,52,17,2,10,6.0,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
34,1498922,52,18,2,10,14.0,196,6,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
35,180919,52,19,3,8,8.0,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Average orders,27
36,2695875,52,21,5,10,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,27
37,3205960,67,1,3,11,0.0,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Most orders,23
38,970922,67,2,1,15,5.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,23
39,596585,67,3,1,13,7.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,23
40,2037087,67,4,2,9,8.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,23
41,2474111,67,5,3,14,8.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Most orders,23
42,1568481,67,6,3,12,7.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Most orders,23
43,2048527,67,8,2,11,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,23
44,2389031,67,9,2,14,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,23
45,2378562,67,10,1,10,6.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,23
46,1515698,67,11,1,11,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,23
47,1928050,67,12,2,12,8.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,23
48,1949274,67,13,1,10,6.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,23
49,551869,67,14,1,9,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,23
50,768572,67,16,4,10,9.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Least busy days,Most orders,23
51,150528,67,18,5,16,4.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,23
52,29758,67,19,0,14,9.0,196,2,1,Soda,77,7,9.0,Mid-range product,Busiest day,Busiest days,Most orders,23
53,1558976,67,21,1,9,5.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,23
54,863974,67,22,1,11,14.0,196,3,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,23
55,2308399,67,23,1,14,14.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,23
56,2759128,81,3,1,9,14.0,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,5
57,1812985,81,5,2,20,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Average orders,5
58,1889835,82,1,3,15,0.0,196,6,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Most orders,19
59,499460,82,3,5,10,5.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,19
60,2728456,82,4,0,11,16.0,196,1,1,Soda,77,7,9.0,Mid-range product,Busiest day,Busiest days,Most orders,19
61,2653743,82,6,4,9,13.0,196,5,1,Soda,77,7,9.0,Mid-range product,Least busy,Least busy days,Most orders,19
62,1358880,82,9,1,10,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,19
63,343588,82,10,2,11,1.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,19
64,3034663,82,15,2,11,12.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,19
65,147262,82,18,1,13,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,19
66,3144004,82,19,2,15,8.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,19
67,2126069,98,3,0,9,25.0,196,7,0,Soda,77,7,9.0,Mid-range product,Busiest day,Busiest days,Most orders,14
68,2210120,98,7,5,14,5.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,14
69,681011,98,9,3,9,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Most orders,14
70,2846344,98,11,4,13,15.0,196,2,1,Soda,77,7,9.0,Mid-range product,Least busy,Least busy days,Most orders,14
71,747431,98,12,6,13,30.0,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,14
72,2383054,98,13,4,11,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Least busy days,Most orders,14
73,1993729,98,14,5,8,8.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Average orders,14
74,1403849,109,3,3,17,9.0,196,5,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Most orders,3
75,520620,120,1,3,11,0.0,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Most orders,3
76,3273029,120,3,2,8,19.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Average orders,3
77,1861943,185,2,1,12,25.0,196,10,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,2
78,2040988,195,1,1,14,0.0,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,57
79,1680569,195,8,1,9,4.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,57
80,276171,195,19,5,11,3.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,57
81,2744976,195,22,5,10,7.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,57
82,2781919,195,25,1,14,4.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,57
83,1738718,195,31,2,8,4.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Average orders,57
84,3058369,195,34,3,10,6.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Most orders,57
85,1485596,195,37,2,15,0.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,57
86,417035,195,40,3,16,2.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Most orders,57
87,1615297,195,47,5,10,2.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,57
88,1765587,195,52,3,12,2.0,196,3,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Most orders,57
89,745908,195,57,4,11,3.0,196,3,1,Soda,77,7,9.0,Mid-range product,Least busy,Least busy days,Most orders,57
90,2505656,222,17,2,12,1.0,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,38
91,3268370,222,38,5,15,1.0,196,6,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,38
92,2016711,290,9,5,19,6.0,196,8,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Average orders,45
93,2706088,290,28,6,10,7.0,196,16,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,45
94,1952286,331,6,5,16,30.0,196,8,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,6
95,3226575,360,1,5,12,0.0,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,1
96,1469869,377,3,5,17,3.0,196,9,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Most orders,3
97,1927023,387,2,4,10,22.0,196,3,0,Soda,77,7,9.0,Mid-range product,Least busy,Least busy days,Most orders,2
98,858092,420,4,1,19,30.0,196,2,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Average orders,5
99,119314,420,5,3,19,16.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Average orders,5

In [30]:
df.loc[df['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [31]:
df.loc[(df['max_order'] <= 40) & (df['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [32]:
df.loc[df['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [33]:
df.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag
0,2539329,1,1,2,8,0.0,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy days,Average orders,10,New customer
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Average orders,10,New customer
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Least busy days,Most orders,10,New customer
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Least busy days,Average orders,10,New customer
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Least busy days,Most orders,10,New customer

In [22]:
df['loyalty_flag'].value_counts()

Regular customer    463844
Loyal customer      335086
New customer        201070
Name: loyalty_flag, dtype: int64

In [23]:
df[['user_id', 'order_number', 'loyalty_flag', 'max_order' ]].head(30)

    user_id  order_number      loyalty_flag  max_order
0         1             1      New customer         10
1         1             2      New customer         10
2         1             3      New customer         10
3         1             4      New customer         10
4         1             5      New customer         10
5         1             6      New customer         10
6         1             7      New customer         10
7         1             8      New customer         10
8         1             9      New customer         10
9         1            10      New customer         10
10       15            15  Regular customer         22
11       15            17  Regular customer         22
12       15            18  Regular customer         22
13       15            21  Regular customer         22
14       15            22  Regular customer         22
15       19             2      New customer          7
16       19             5      New customer          7
17       19             7      New customer          7
18       21            10  Regular customer         33
19       31            10  Regular customer         17
20       31            17  Regular customer         17
21       43             6      New customer          9
22       43             9      New customer          9
23       52             1  Regular customer         27
24       52             2  Regular customer         27
25       52             3  Regular customer         27
26       52             5  Regular customer         27
27       52             7  Regular customer         27
28       52             9  Regular customer         27
29       52            10  Regular customer         27

In [24]:
df.to_pickle(os.path.join(path, "Prepped Data", "ords_prods_merged_SUBSET.pkl"))